import { readFileSync, writeFileSync } from "node:fs";
const html = readFileSync(new URL("./admin-ui.html", import.meta.url), "utf8");
writeFileSync(new URL("./admin-ui.js", import.meta.url), "// Generated by build-ui.mjs from admin-ui.html. Do not edit.\nexport default " + JSON.stringify(html) + ";\n");
